language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run test

# Send coverage data to Coveralls
after_script: "jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
